spring:
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        type: trace
  datasource:
    url: jdbc:mysql://localhost:3306/ticker_service
    username: root
    password: root
logging:
  level:
    org:
      hibernate:
        type: trace
